# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled_V13_3.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1350, 731)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(1100, 20, 231, 25))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Load_btn = QtWidgets.QPushButton(self.layoutWidget)
        self.Load_btn.setObjectName("Load_btn")
        self.horizontalLayout.addWidget(self.Load_btn)
        self.Run_btn = QtWidgets.QPushButton(self.layoutWidget)
        self.Run_btn.setObjectName("Run_btn")
        self.horizontalLayout.addWidget(self.Run_btn)
        self.tabWidget_fig = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget_fig.setGeometry(QtCore.QRect(10, 0, 1081, 701))
        self.tabWidget_fig.setObjectName("tabWidget_fig")
        self.Figure = QtWidgets.QWidget()
        self.Figure.setObjectName("Figure")
        self.layoutWidget1 = QtWidgets.QWidget(self.Figure)
        self.layoutWidget1.setGeometry(QtCore.QRect(0, 0, 1071, 671))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Conduct_Length_fig = QtWidgets.QGroupBox(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Conduct_Length_fig.sizePolicy().hasHeightForWidth())
        self.Conduct_Length_fig.setSizePolicy(sizePolicy)
        self.Conduct_Length_fig.setMaximumSize(QtCore.QSize(352, 669))
        self.Conduct_Length_fig.setObjectName("Conduct_Length_fig")
        self.horizontalLayout_2.addWidget(self.Conduct_Length_fig)
        self.Conductance_fig = QtWidgets.QGroupBox(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Conductance_fig.sizePolicy().hasHeightForWidth())
        self.Conductance_fig.setSizePolicy(sizePolicy)
        self.Conductance_fig.setMaximumSize(QtCore.QSize(352, 669))
        self.Conductance_fig.setObjectName("Conductance_fig")
        self.horizontalLayout_2.addWidget(self.Conductance_fig)
        self.Length_fig = QtWidgets.QGroupBox(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Length_fig.sizePolicy().hasHeightForWidth())
        self.Length_fig.setSizePolicy(sizePolicy)
        self.Length_fig.setMaximumSize(QtCore.QSize(352, 669))
        self.Length_fig.setObjectName("Length_fig")
        self.horizontalLayout_2.addWidget(self.Length_fig)
        self.tabWidget_fig.addTab(self.Figure, "")
        self.Single_Trace = QtWidgets.QWidget()
        self.Single_Trace.setObjectName("Single_Trace")
        self.groupBox_4 = QtWidgets.QGroupBox(self.Single_Trace)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 10, 391, 661))
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.Single_Trace)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(420, 500, 171, 161))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.QPB_Add_to_save = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.QPB_Add_to_save.setObjectName("QPB_Add_to_save")
        self.gridLayout_3.addWidget(self.QPB_Add_to_save, 2, 0, 1, 1)
        self.QPB_save_all_trace = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.QPB_save_all_trace.setObjectName("QPB_save_all_trace")
        self.gridLayout_3.addWidget(self.QPB_save_all_trace, 3, 0, 1, 2)
        self.QPB_save_add = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.QPB_save_add.setObjectName("QPB_save_add")
        self.gridLayout_3.addWidget(self.QPB_save_add, 2, 1, 1, 1)
        self.QPB_Prev = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.QPB_Prev.setObjectName("QPB_Prev")
        self.gridLayout_3.addWidget(self.QPB_Prev, 1, 1, 1, 1)
        self.QPB_First = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.QPB_First.setObjectName("QPB_First")
        self.gridLayout_3.addWidget(self.QPB_First, 0, 0, 1, 1)
        self.QPB_Next = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.QPB_Next.setObjectName("QPB_Next")
        self.gridLayout_3.addWidget(self.QPB_Next, 1, 0, 1, 1)
        self.QPB_Last = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.QPB_Last.setObjectName("QPB_Last")
        self.gridLayout_3.addWidget(self.QPB_Last, 0, 1, 1, 1)
        self.gridLayoutWidget_3.raise_()
        self.groupBox_4.raise_()
        self.tabWidget_fig.addTab(self.Single_Trace, "")
        self.Frequency = QtWidgets.QWidget()
        self.Frequency.setObjectName("Frequency")
        self.groupBox_5 = QtWidgets.QGroupBox(self.Frequency)
        self.groupBox_5.setGeometry(QtCore.QRect(19, 91, 1041, 341))
        self.groupBox_5.setObjectName("groupBox_5")
        self.tabWidget_fig.addTab(self.Frequency, "")
        self.Function = QtWidgets.QTabWidget(self.centralwidget)
        self.Function.setGeometry(QtCore.QRect(1101, 60, 241, 441))
        self.Function.setObjectName("Function")
        self.Analysis = QtWidgets.QWidget()
        self.Analysis.setObjectName("Analysis")
        self.process = QtWidgets.QGroupBox(self.Analysis)
        self.process.setGeometry(QtCore.QRect(10, 50, 121, 41))
        self.process.setObjectName("process")
        self.layoutWidget2 = QtWidgets.QWidget(self.process)
        self.layoutWidget2.setGeometry(QtCore.QRect(13, 18, 108, 18))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.QRB_open = QtWidgets.QRadioButton(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.QRB_open.sizePolicy().hasHeightForWidth())
        self.QRB_open.setSizePolicy(sizePolicy)
        self.QRB_open.setMaximumSize(QtCore.QSize(47, 16))
        self.QRB_open.setObjectName("QRB_open")
        self.horizontalLayout_3.addWidget(self.QRB_open)
        self.QRB_close = QtWidgets.QRadioButton(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.QRB_close.sizePolicy().hasHeightForWidth())
        self.QRB_close.setSizePolicy(sizePolicy)
        self.QRB_close.setMaximumSize(QtCore.QSize(53, 16))
        self.QRB_close.setObjectName("QRB_close")
        self.horizontalLayout_3.addWidget(self.QRB_close)
        self.groupBox_6 = QtWidgets.QGroupBox(self.Analysis)
        self.groupBox_6.setGeometry(QtCore.QRect(10, 5, 121, 45))
        self.groupBox_6.setObjectName("groupBox_6")
        self.CB_style = QtWidgets.QComboBox(self.groupBox_6)
        self.CB_style.setGeometry(QtCore.QRect(5, 18, 110, 20))
        self.CB_style.setObjectName("CB_style")
        self.groupBox_11 = QtWidgets.QGroupBox(self.Analysis)
        self.groupBox_11.setGeometry(QtCore.QRect(138, 5, 91, 45))
        self.groupBox_11.setObjectName("groupBox_11")
        self.FitMode_box = QtWidgets.QComboBox(self.groupBox_11)
        self.FitMode_box.setGeometry(QtCore.QRect(9, 18, 71, 20))
        self.FitMode_box.setObjectName("FitMode_box")
        self.FitMode_box.addItem("")
        self.FitMode_box.addItem("")
        self.FitMode_box.addItem("")
        self.QPB_redraw = QtWidgets.QPushButton(self.Analysis)
        self.QPB_redraw.setGeometry(QtCore.QRect(145, 60, 75, 28))
        self.QPB_redraw.setObjectName("QPB_redraw")
        self.Parameter = QtWidgets.QTabWidget(self.Analysis)
        self.Parameter.setGeometry(QtCore.QRect(0, 93, 236, 324))
        self.Parameter.setObjectName("Parameter")
        self.Basic = QtWidgets.QWidget()
        self.Basic.setObjectName("Basic")
        self.line_2 = QtWidgets.QFrame(self.Basic)
        self.line_2.setGeometry(QtCore.QRect(0, 235, 231, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.Basic)
        self.line_3.setGeometry(QtCore.QRect(0, 198, 231, 16))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.QPB_reset = QtWidgets.QPushButton(self.Basic)
        self.QPB_reset.setGeometry(QtCore.QRect(12, 250, 61, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.QPB_reset.sizePolicy().hasHeightForWidth())
        self.QPB_reset.setSizePolicy(sizePolicy)
        self.QPB_reset.setMaximumSize(QtCore.QSize(61, 23))
        self.QPB_reset.setObjectName("QPB_reset")
        self.QPB_save_all = QtWidgets.QPushButton(self.Basic)
        self.QPB_save_all.setGeometry(QtCore.QRect(79, 250, 61, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.QPB_save_all.sizePolicy().hasHeightForWidth())
        self.QPB_save_all.setSizePolicy(sizePolicy)
        self.QPB_save_all.setMaximumSize(QtCore.QSize(61, 23))
        self.QPB_save_all.setObjectName("QPB_save_all")
        self.QPB_save_goodtrace = QtWidgets.QPushButton(self.Basic)
        self.QPB_save_goodtrace.setGeometry(QtCore.QRect(146, 250, 75, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.QPB_save_goodtrace.sizePolicy().hasHeightForWidth())
        self.QPB_save_goodtrace.setSizePolicy(sizePolicy)
        self.QPB_save_goodtrace.setMaximumSize(QtCore.QSize(75, 23))
        self.QPB_save_goodtrace.setObjectName("QPB_save_goodtrace")
        self.layoutWidget3 = QtWidgets.QWidget(self.Basic)
        self.layoutWidget3.setGeometry(QtCore.QRect(10, 210, 210, 27))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_52 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_52.setAlignment(QtCore.Qt.AlignCenter)
        self.label_52.setObjectName("label_52")
        self.horizontalLayout_4.addWidget(self.label_52)
        self.QPT_add_length = QtWidgets.QPlainTextEdit(self.layoutWidget3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.QPT_add_length.sizePolicy().hasHeightForWidth())
        self.QPT_add_length.setSizePolicy(sizePolicy)
        self.QPT_add_length.setMaximumSize(QtCore.QSize(61, 25))
        self.QPT_add_length.setObjectName("QPT_add_length")
        self.horizontalLayout_4.addWidget(self.QPT_add_length)
        self.QPB_update = QtWidgets.QPushButton(self.layoutWidget3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.QPB_update.sizePolicy().hasHeightForWidth())
        self.QPB_update.setSizePolicy(sizePolicy)
        self.QPB_update.setMaximumSize(QtCore.QSize(75, 23))
        self.QPB_update.setObjectName("QPB_update")
        self.horizontalLayout_4.addWidget(self.QPB_update)
        self.toolBox = QtWidgets.QToolBox(self.Basic)
        self.toolBox.setGeometry(QtCore.QRect(5, 3, 221, 191))
        self.toolBox.setObjectName("toolBox")
        self.Cut_set = QtWidgets.QWidget()
        self.Cut_set.setGeometry(QtCore.QRect(0, 0, 221, 139))
        self.Cut_set.setObjectName("Cut_set")
        self.layoutWidget4 = QtWidgets.QWidget(self.Cut_set)
        self.layoutWidget4.setGeometry(QtCore.QRect(10, 3, 201, 131))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.layoutWidget4)
        self.gridLayout_11.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.QPT_high_cut = QtWidgets.QPlainTextEdit(self.layoutWidget4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.QPT_high_cut.sizePolicy().hasHeightForWidth())
        self.QPT_high_cut.setSizePolicy(sizePolicy)
        self.QPT_high_cut.setMaximumSize(QtCore.QSize(80, 25))
        self.QPT_high_cut.setObjectName("QPT_high_cut")
        self.gridLayout_11.addWidget(self.QPT_high_cut, 0, 0, 1, 1)
        self.QPT_low_cut = QtWidgets.QPlainTextEdit(self.layoutWidget4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.QPT_low_cut.sizePolicy().hasHeightForWidth())
        self.QPT_low_cut.setSizePolicy(sizePolicy)
        self.QPT_low_cut.setMaximumSize(QtCore.QSize(80, 25))
        self.QPT_low_cut.setObjectName("QPT_low_cut")
        self.gridLayout_11.addWidget(self.QPT_low_cut, 0, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setMaximumSize(QtCore.QSize(48, 16))
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_11.addWidget(self.label_6, 1, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setMaximumSize(QtCore.QSize(42, 16))
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_11.addWidget(self.label_7, 1, 1, 1, 1)
        self.QPT_high_length = QtWidgets.QPlainTextEdit(self.layoutWidget4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.QPT_high_length.sizePolicy().hasHeightForWidth())
        self.QPT_high_length.setSizePolicy(sizePolicy)
        self.QPT_high_length.setMaximumSize(QtCore.QSize(80, 25))
        self.QPT_high_length.setObjectName("QPT_high_length")
        self.gridLayout_11.addWidget(self.QPT_high_length, 2, 0, 1, 1)
        self.QPT_low_length = QtWidgets.QPlainTextEdit(self.layoutWidget4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.QPT_low_length.sizePolicy().hasHeightForWidth())
        self.QPT_low_length.setSizePolicy(sizePolicy)
        self.QPT_low_length.setMaximumSize(QtCore.QSize(80, 25))
        self.QPT_low_length.setObjectName("QPT_low_length")
        self.gridLayout_11.addWidget(self.QPT_low_length, 2, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setMaximumSize(QtCore.QSize(66, 16))
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_11.addWidget(self.label_8, 3, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setMaximumSize(QtCore.QSize(60, 16))
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_11.addWidget(self.label_9, 3, 1, 1, 1)
        self.label_64 = QtWidgets.QLabel(self.layoutWidget4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_64.sizePolicy().hasHeightForWidth())
        self.label_64.setSizePolicy(sizePolicy)
        self.label_64.setMaximumSize(QtCore.QSize(66, 16))
        self.label_64.setAlignment(QtCore.Qt.AlignCenter)
        self.label_64.setObjectName("label_64")
        self.gridLayout_11.addWidget(self.label_64, 4, 0, 1, 1)
        self.QPT_zero_set = QtWidgets.QPlainTextEdit(self.layoutWidget4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.QPT_zero_set.sizePolicy().hasHeightForWidth())
        self.QPT_zero_set.setSizePolicy(sizePolicy)
        self.QPT_zero_set.setMaximumSize(QtCore.QSize(80, 25))
        self.QPT_zero_set.setObjectName("QPT_zero_set")
        self.gridLayout_11.addWidget(self.QPT_zero_set, 4, 1, 1, 1)
        self.toolBox.addItem(self.Cut_set, "")
        self.Para = QtWidgets.QWidget()
        self.Para.setGeometry(QtCore.QRect(0, 0, 221, 139))
        self.Para.setObjectName("Para")
        self.layoutWidget5 = QtWidgets.QWidget(self.Para)
        self.layoutWidget5.setGeometry(QtCore.QRect(2, 10, 208, 94))
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.layoutWidget5)
        self.gridLayout_10.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.QPT_sampling_rate = QtWidgets.QPlainTextEdit(self.layoutWidget5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.QPT_sampling_rate.sizePolicy().hasHeightForWidth())
        self.QPT_sampling_rate.setSizePolicy(sizePolicy)
        self.QPT_sampling_rate.setMinimumSize(QtCore.QSize(0, 0))
        self.QPT_sampling_rate.setMaximumSize(QtCore.QSize(74, 25))
        self.QPT_sampling_rate.setObjectName("QPT_sampling_rate")
        self.gridLayout_10.addWidget(self.QPT_sampling_rate, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget5)
        self.label_4.setObjectName("label_4")
        self.gridLayout_10.addWidget(self.label_4, 0, 1, 1, 1)
        self.QPT_piezo_rate = QtWidgets.QPlainTextEdit(self.layoutWidget5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.QPT_piezo_rate.sizePolicy().hasHeightForWidth())
        self.QPT_piezo_rate.setSizePolicy(sizePolicy)
        self.QPT_piezo_rate.setMaximumSize(QtCore.QSize(74, 25))
        self.QPT_piezo_rate.setPlainText("")
        self.QPT_piezo_rate.setObjectName("QPT_piezo_rate")
        self.gridLayout_10.addWidget(self.QPT_piezo_rate, 0, 2, 1, 1)
        self.label_63 = QtWidgets.QLabel(self.layoutWidget5)
        self.label_63.setObjectName("label_63")
        self.gridLayout_10.addWidget(self.label_63, 0, 3, 1, 1)
        self.label = QtWidgets.QLabel(self.layoutWidget5)
        self.label.setObjectName("label")
        self.gridLayout_10.addWidget(self.label, 1, 0, 1, 1)
        self.label_62 = QtWidgets.QLabel(self.layoutWidget5)
        self.label_62.setObjectName("label_62")
        self.gridLayout_10.addWidget(self.label_62, 1, 2, 1, 1)
        self.QPT_biasV = QtWidgets.QPlainTextEdit(self.layoutWidget5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.QPT_biasV.sizePolicy().hasHeightForWidth())
        self.QPT_biasV.setSizePolicy(sizePolicy)
        self.QPT_biasV.setMaximumSize(QtCore.QSize(74, 25))
        self.QPT_biasV.setObjectName("QPT_biasV")
        self.gridLayout_10.addWidget(self.QPT_biasV, 2, 0, 1, 1)
        self.label_61 = QtWidgets.QLabel(self.layoutWidget5)
        self.label_61.setObjectName("label_61")
        self.gridLayout_10.addWidget(self.label_61, 2, 1, 1, 1)
        self.QPT_strecting_rate = QtWidgets.QPlainTextEdit(self.layoutWidget5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.QPT_strecting_rate.sizePolicy().hasHeightForWidth())
        self.QPT_strecting_rate.setSizePolicy(sizePolicy)
        self.QPT_strecting_rate.setMaximumSize(QtCore.QSize(74, 25))
        self.QPT_strecting_rate.setObjectName("QPT_strecting_rate")
        self.gridLayout_10.addWidget(self.QPT_strecting_rate, 2, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget5)
        self.label_5.setObjectName("label_5")
        self.gridLayout_10.addWidget(self.label_5, 2, 3, 1, 1)
        self.label_60 = QtWidgets.QLabel(self.layoutWidget5)
        self.label_60.setAlignment(QtCore.Qt.AlignCenter)
        self.label_60.setObjectName("label_60")
        self.gridLayout_10.addWidget(self.label_60, 3, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget5)
        self.label_3.setObjectName("label_3")
        self.gridLayout_10.addWidget(self.label_3, 3, 2, 1, 2)
        self.toolBox.addItem(self.Para, "")
        self.Parameter.addTab(self.Basic, "")
        self.Fig_set = QtWidgets.QWidget()
        self.Fig_set.setObjectName("Fig_set")
        self.groupBox = QtWidgets.QGroupBox(self.Fig_set)
        self.groupBox.setGeometry(QtCore.QRect(0, 0, 230, 112))
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget6 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget6.setGeometry(QtCore.QRect(11, 15, 216, 89))
        self.layoutWidget6.setObjectName("layoutWidget6")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.layoutWidget6)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_43 = QtWidgets.QLabel(self.layoutWidget6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_43.sizePolicy().hasHeightForWidth())
        self.label_43.setSizePolicy(sizePolicy)
        self.label_43.setMaximumSize(QtCore.QSize(54, 25))
        self.label_43.setAlignment(QtCore.Qt.AlignCenter)
        self.label_43.setObjectName("label_43")
        self.gridLayout_7.addWidget(self.label_43, 0, 0, 1, 1)
        self.QPT_2D_binsx = QtWidgets.QPlainTextEdit(self.layoutWidget6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.QPT_2D_binsx.sizePolicy().hasHeightForWidth())
        self.QPT_2D_binsx.setSizePolicy(sizePolicy)
        self.QPT_2D_binsx.setMinimumSize(QtCore.QSize(0, 0))
        self.QPT_2D_binsx.setMaximumSize(QtCore.QSize(74, 25))
        self.QPT_2D_binsx.setObjectName("QPT_2D_binsx")
        self.gridLayout_7.addWidget(self.QPT_2D_binsx, 0, 1, 1, 1)
        self.QPT_2D_binsy = QtWidgets.QPlainTextEdit(self.layoutWidget6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.QPT_2D_binsy.sizePolicy().hasHeightForWidth())
        self.QPT_2D_binsy.setSizePolicy(sizePolicy)
        self.QPT_2D_binsy.setMinimumSize(QtCore.QSize(0, 0))
        self.QPT_2D_binsy.setMaximumSize(QtCore.QSize(74, 25))
        self.QPT_2D_binsy.setObjectName("QPT_2D_binsy")
        self.gridLayout_7.addWidget(self.QPT_2D_binsy, 0, 2, 1, 1)
        self.label_46 = QtWidgets.QLabel(self.layoutWidget6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_46.sizePolicy().hasHeightForWidth())
        self.label_46.setSizePolicy(sizePolicy)
        self.label_46.setMaximumSize(QtCore.QSize(54, 25))
        self.label_46.setAlignment(QtCore.Qt.AlignCenter)
        self.label_46.setObjectName("label_46")
        self.gridLayout_7.addWidget(self.label_46, 1, 0, 1, 1)
        self.QPT_2D_xlim_l = QtWidgets.QPlainTextEdit(self.layoutWidget6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.QPT_2D_xlim_l.sizePolicy().hasHeightForWidth())
        self.QPT_2D_xlim_l.setSizePolicy(sizePolicy)
        self.QPT_2D_xlim_l.setMinimumSize(QtCore.QSize(0, 0))
        self.QPT_2D_xlim_l.setMaximumSize(QtCore.QSize(74, 25))
        self.QPT_2D_xlim_l.setObjectName("QPT_2D_xlim_l")
        self.gridLayout_7.addWidget(self.QPT_2D_xlim_l, 1, 1, 1, 1)
        self.QPT_2D_xlim_r = QtWidgets.QPlainTextEdit(self.layoutWidget6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.QPT_2D_xlim_r.sizePolicy().hasHeightForWidth())
        self.QPT_2D_xlim_r.setSizePolicy(sizePolicy)
        self.QPT_2D_xlim_r.setMinimumSize(QtCore.QSize(0, 0))
        self.QPT_2D_xlim_r.setMaximumSize(QtCore.QSize(74, 25))
        self.QPT_2D_xlim_r.setObjectName("QPT_2D_xlim_r")
        self.gridLayout_7.addWidget(self.QPT_2D_xlim_r, 1, 2, 1, 1)
        self.label_47 = QtWidgets.QLabel(self.layoutWidget6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_47.sizePolicy().hasHeightForWidth())
        self.label_47.setSizePolicy(sizePolicy)
        self.label_47.setMaximumSize(QtCore.QSize(54, 25))
        self.label_47.setAlignment(QtCore.Qt.AlignCenter)
        self.label_47.setObjectName("label_47")
        self.gridLayout_7.addWidget(self.label_47, 2, 0, 1, 1)
        self.QPT_2D_ylim_l = QtWidgets.QPlainTextEdit(self.layoutWidget6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.QPT_2D_ylim_l.sizePolicy().hasHeightForWidth())
        self.QPT_2D_ylim_l.setSizePolicy(sizePolicy)
        self.QPT_2D_ylim_l.setMinimumSize(QtCore.QSize(0, 0))
        self.QPT_2D_ylim_l.setMaximumSize(QtCore.QSize(74, 25))
        self.QPT_2D_ylim_l.setObjectName("QPT_2D_ylim_l")
        self.gridLayout_7.addWidget(self.QPT_2D_ylim_l, 2, 1, 1, 1)
        self.QPT_2D_ylim_r = QtWidgets.QPlainTextEdit(self.layoutWidget6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.QPT_2D_ylim_r.sizePolicy().hasHeightForWidth())
        self.QPT_2D_ylim_r.setSizePolicy(sizePolicy)
        self.QPT_2D_ylim_r.setMinimumSize(QtCore.QSize(0, 0))
        self.QPT_2D_ylim_r.setMaximumSize(QtCore.QSize(74, 25))
        self.QPT_2D_ylim_r.setObjectName("QPT_2D_ylim_r")
        self.gridLayout_7.addWidget(self.QPT_2D_ylim_r, 2, 2, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.Fig_set)
        self.groupBox_2.setGeometry(QtCore.QRect(0, 110, 230, 81))
        self.groupBox_2.setObjectName("groupBox_2")
        self.layoutWidget7 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget7.setGeometry(QtCore.QRect(10, 10, 211, 58))
        self.layoutWidget7.setObjectName("layoutWidget7")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget7)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_48 = QtWidgets.QLabel(self.layoutWidget7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_48.sizePolicy().hasHeightForWidth())
        self.label_48.setSizePolicy(sizePolicy)
        self.label_48.setMaximumSize(QtCore.QSize(54, 25))
        self.label_48.setAlignment(QtCore.Qt.AlignCenter)
        self.label_48.setObjectName("label_48")
        self.gridLayout_2.addWidget(self.label_48, 0, 0, 1, 1)
        self.QPT_1D_bins = QtWidgets.QPlainTextEdit(self.layoutWidget7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.QPT_1D_bins.sizePolicy().hasHeightForWidth())
        self.QPT_1D_bins.setSizePolicy(sizePolicy)
        self.QPT_1D_bins.setMinimumSize(QtCore.QSize(0, 0))
        self.QPT_1D_bins.setMaximumSize(QtCore.QSize(74, 25))
        self.QPT_1D_bins.setObjectName("QPT_1D_bins")
        self.gridLayout_2.addWidget(self.QPT_1D_bins, 0, 1, 1, 1)
        self.QPB_1D_color = QtWidgets.QPushButton(self.layoutWidget7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.QPB_1D_color.sizePolicy().hasHeightForWidth())
        self.QPB_1D_color.setSizePolicy(sizePolicy)
        self.QPB_1D_color.setMaximumSize(QtCore.QSize(74, 25))
        self.QPB_1D_color.setObjectName("QPB_1D_color")
        self.gridLayout_2.addWidget(self.QPB_1D_color, 0, 2, 1, 1)
        self.label_53 = QtWidgets.QLabel(self.layoutWidget7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_53.sizePolicy().hasHeightForWidth())
        self.label_53.setSizePolicy(sizePolicy)
        self.label_53.setMaximumSize(QtCore.QSize(54, 25))
        self.label_53.setAlignment(QtCore.Qt.AlignCenter)
        self.label_53.setObjectName("label_53")
        self.gridLayout_2.addWidget(self.label_53, 1, 0, 1, 1)
        self.QPT_1D_xlim_l = QtWidgets.QPlainTextEdit(self.layoutWidget7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.QPT_1D_xlim_l.sizePolicy().hasHeightForWidth())
        self.QPT_1D_xlim_l.setSizePolicy(sizePolicy)
        self.QPT_1D_xlim_l.setMinimumSize(QtCore.QSize(0, 0))
        self.QPT_1D_xlim_l.setMaximumSize(QtCore.QSize(74, 25))
        self.QPT_1D_xlim_l.setObjectName("QPT_1D_xlim_l")
        self.gridLayout_2.addWidget(self.QPT_1D_xlim_l, 1, 1, 1, 1)
        self.QPT_1D_xlim_r = QtWidgets.QPlainTextEdit(self.layoutWidget7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.QPT_1D_xlim_r.sizePolicy().hasHeightForWidth())
        self.QPT_1D_xlim_r.setSizePolicy(sizePolicy)
        self.QPT_1D_xlim_r.setMinimumSize(QtCore.QSize(0, 0))
        self.QPT_1D_xlim_r.setMaximumSize(QtCore.QSize(74, 25))
        self.QPT_1D_xlim_r.setObjectName("QPT_1D_xlim_r")
        self.gridLayout_2.addWidget(self.QPT_1D_xlim_r, 1, 2, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.Fig_set)
        self.groupBox_3.setGeometry(QtCore.QRect(0, 190, 230, 75))
        self.groupBox_3.setObjectName("groupBox_3")
        self.layoutWidget8 = QtWidgets.QWidget(self.groupBox_3)
        self.layoutWidget8.setGeometry(QtCore.QRect(10, 10, 221, 58))
        self.layoutWidget8.setObjectName("layoutWidget8")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.layoutWidget8)
        self.gridLayout_9.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_49 = QtWidgets.QLabel(self.layoutWidget8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_49.sizePolicy().hasHeightForWidth())
        self.label_49.setSizePolicy(sizePolicy)
        self.label_49.setMaximumSize(QtCore.QSize(54, 25))
        self.label_49.setAlignment(QtCore.Qt.AlignCenter)
        self.label_49.setObjectName("label_49")
        self.gridLayout_9.addWidget(self.label_49, 1, 0, 1, 1)
        self.QPT_leng_xlim_l = QtWidgets.QPlainTextEdit(self.layoutWidget8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.QPT_leng_xlim_l.sizePolicy().hasHeightForWidth())
        self.QPT_leng_xlim_l.setSizePolicy(sizePolicy)
        self.QPT_leng_xlim_l.setMinimumSize(QtCore.QSize(0, 0))
        self.QPT_leng_xlim_l.setMaximumSize(QtCore.QSize(74, 25))
        self.QPT_leng_xlim_l.setObjectName("QPT_leng_xlim_l")
        self.gridLayout_9.addWidget(self.QPT_leng_xlim_l, 0, 1, 1, 1)
        self.QPT_leng_bins = QtWidgets.QPlainTextEdit(self.layoutWidget8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.QPT_leng_bins.sizePolicy().hasHeightForWidth())
        self.QPT_leng_bins.setSizePolicy(sizePolicy)
        self.QPT_leng_bins.setMinimumSize(QtCore.QSize(0, 0))
        self.QPT_leng_bins.setMaximumSize(QtCore.QSize(74, 25))
        self.QPT_leng_bins.setObjectName("QPT_leng_bins")
        self.gridLayout_9.addWidget(self.QPT_leng_bins, 1, 1, 1, 1)
        self.QPT_leng_xlim_r = QtWidgets.QPlainTextEdit(self.layoutWidget8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.QPT_leng_xlim_r.sizePolicy().hasHeightForWidth())
        self.QPT_leng_xlim_r.setSizePolicy(sizePolicy)
        self.QPT_leng_xlim_r.setMinimumSize(QtCore.QSize(0, 0))
        self.QPT_leng_xlim_r.setMaximumSize(QtCore.QSize(74, 25))
        self.QPT_leng_xlim_r.setObjectName("QPT_leng_xlim_r")
        self.gridLayout_9.addWidget(self.QPT_leng_xlim_r, 0, 2, 1, 1)
        self.label_51 = QtWidgets.QLabel(self.layoutWidget8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_51.sizePolicy().hasHeightForWidth())
        self.label_51.setSizePolicy(sizePolicy)
        self.label_51.setMaximumSize(QtCore.QSize(54, 25))
        self.label_51.setAlignment(QtCore.Qt.AlignCenter)
        self.label_51.setObjectName("label_51")
        self.gridLayout_9.addWidget(self.label_51, 0, 0, 1, 1)
        self.Parameter.addTab(self.Fig_set, "")
        self.Function.addTab(self.Analysis, "")
        self.Select = QtWidgets.QWidget()
        self.Select.setObjectName("Select")
        self.groupBox_8 = QtWidgets.QGroupBox(self.Select)
        self.groupBox_8.setGeometry(QtCore.QRect(1, 1, 231, 231))
        self.groupBox_8.setTitle("")
        self.groupBox_8.setObjectName("groupBox_8")
        self.layoutWidget9 = QtWidgets.QWidget(self.groupBox_8)
        self.layoutWidget9.setGeometry(QtCore.QRect(8, 14, 210, 213))
        self.layoutWidget9.setObjectName("layoutWidget9")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.layoutWidget9)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.QPT_start1 = QtWidgets.QPlainTextEdit(self.layoutWidget9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.QPT_start1.sizePolicy().hasHeightForWidth())
        self.QPT_start1.setSizePolicy(sizePolicy)
        self.QPT_start1.setMaximumSize(QtCore.QSize(101, 28))
        self.QPT_start1.setObjectName("QPT_start1")
        self.gridLayout_4.addWidget(self.QPT_start1, 0, 0, 1, 1)
        self.QPT_end1 = QtWidgets.QPlainTextEdit(self.layoutWidget9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.QPT_end1.sizePolicy().hasHeightForWidth())
        self.QPT_end1.setSizePolicy(sizePolicy)
        self.QPT_end1.setMaximumSize(QtCore.QSize(101, 28))
        self.QPT_end1.setObjectName("QPT_end1")
        self.gridLayout_4.addWidget(self.QPT_end1, 0, 1, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.layoutWidget9)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.gridLayout_4.addWidget(self.label_19, 1, 0, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.layoutWidget9)
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.gridLayout_4.addWidget(self.label_20, 1, 1, 1, 1)
        self.QPT_lower_limit1 = QtWidgets.QPlainTextEdit(self.layoutWidget9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.QPT_lower_limit1.sizePolicy().hasHeightForWidth())
        self.QPT_lower_limit1.setSizePolicy(sizePolicy)
        self.QPT_lower_limit1.setMaximumSize(QtCore.QSize(101, 28))
        self.QPT_lower_limit1.setObjectName("QPT_lower_limit1")
        self.gridLayout_4.addWidget(self.QPT_lower_limit1, 2, 0, 1, 1)
        self.QPT_upper_limit1 = QtWidgets.QPlainTextEdit(self.layoutWidget9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.QPT_upper_limit1.sizePolicy().hasHeightForWidth())
        self.QPT_upper_limit1.setSizePolicy(sizePolicy)
        self.QPT_upper_limit1.setMaximumSize(QtCore.QSize(101, 28))
        self.QPT_upper_limit1.setObjectName("QPT_upper_limit1")
        self.gridLayout_4.addWidget(self.QPT_upper_limit1, 2, 1, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.layoutWidget9)
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.gridLayout_4.addWidget(self.label_21, 3, 0, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.layoutWidget9)
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.gridLayout_4.addWidget(self.label_22, 3, 1, 1, 1)
        self.line = QtWidgets.QFrame(self.layoutWidget9)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_4.addWidget(self.line, 4, 0, 1, 2)
        self.QPT_start2 = QtWidgets.QPlainTextEdit(self.layoutWidget9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.QPT_start2.sizePolicy().hasHeightForWidth())
        self.QPT_start2.setSizePolicy(sizePolicy)
        self.QPT_start2.setMaximumSize(QtCore.QSize(101, 28))
        self.QPT_start2.setObjectName("QPT_start2")
        self.gridLayout_4.addWidget(self.QPT_start2, 5, 0, 1, 1)
        self.QPT_end2 = QtWidgets.QPlainTextEdit(self.layoutWidget9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.QPT_end2.sizePolicy().hasHeightForWidth())
        self.QPT_end2.setSizePolicy(sizePolicy)
        self.QPT_end2.setMaximumSize(QtCore.QSize(101, 28))
        self.QPT_end2.setObjectName("QPT_end2")
        self.gridLayout_4.addWidget(self.QPT_end2, 5, 1, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.layoutWidget9)
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName("label_23")
        self.gridLayout_4.addWidget(self.label_23, 6, 0, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.layoutWidget9)
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName("label_24")
        self.gridLayout_4.addWidget(self.label_24, 6, 1, 1, 1)
        self.QPT_lower_limit2 = QtWidgets.QPlainTextEdit(self.layoutWidget9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.QPT_lower_limit2.sizePolicy().hasHeightForWidth())
        self.QPT_lower_limit2.setSizePolicy(sizePolicy)
        self.QPT_lower_limit2.setMaximumSize(QtCore.QSize(101, 28))
        self.QPT_lower_limit2.setObjectName("QPT_lower_limit2")
        self.gridLayout_4.addWidget(self.QPT_lower_limit2, 7, 0, 1, 1)
        self.QPT_upper_limit2 = QtWidgets.QPlainTextEdit(self.layoutWidget9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.QPT_upper_limit2.sizePolicy().hasHeightForWidth())
        self.QPT_upper_limit2.setSizePolicy(sizePolicy)
        self.QPT_upper_limit2.setMaximumSize(QtCore.QSize(101, 28))
        self.QPT_upper_limit2.setObjectName("QPT_upper_limit2")
        self.gridLayout_4.addWidget(self.QPT_upper_limit2, 7, 1, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.layoutWidget9)
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setObjectName("label_25")
        self.gridLayout_4.addWidget(self.label_25, 8, 0, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.layoutWidget9)
        self.label_26.setAlignment(QtCore.Qt.AlignCenter)
        self.label_26.setObjectName("label_26")
        self.gridLayout_4.addWidget(self.label_26, 8, 1, 1, 1)
        self.groupBox_9 = QtWidgets.QGroupBox(self.Select)
        self.groupBox_9.setGeometry(QtCore.QRect(3, 240, 231, 111))
        self.groupBox_9.setTitle("")
        self.groupBox_9.setObjectName("groupBox_9")
        self.layoutWidget10 = QtWidgets.QWidget(self.groupBox_9)
        self.layoutWidget10.setGeometry(QtCore.QRect(10, 10, 211, 92))
        self.layoutWidget10.setObjectName("layoutWidget10")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.layoutWidget10)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_27 = QtWidgets.QLabel(self.layoutWidget10)
        self.label_27.setObjectName("label_27")
        self.gridLayout_5.addWidget(self.label_27, 0, 0, 1, 1)
        self.QTB_all_trace = QtWidgets.QTextBrowser(self.layoutWidget10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.QTB_all_trace.sizePolicy().hasHeightForWidth())
        self.QTB_all_trace.setSizePolicy(sizePolicy)
        self.QTB_all_trace.setMaximumSize(QtCore.QSize(101, 26))
        self.QTB_all_trace.setObjectName("QTB_all_trace")
        self.gridLayout_5.addWidget(self.QTB_all_trace, 0, 1, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.layoutWidget10)
        self.label_28.setObjectName("label_28")
        self.gridLayout_5.addWidget(self.label_28, 1, 0, 1, 1)
        self.QTB_selected_trace = QtWidgets.QTextBrowser(self.layoutWidget10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.QTB_selected_trace.sizePolicy().hasHeightForWidth())
        self.QTB_selected_trace.setSizePolicy(sizePolicy)
        self.QTB_selected_trace.setMaximumSize(QtCore.QSize(101, 26))
        self.QTB_selected_trace.setObjectName("QTB_selected_trace")
        self.gridLayout_5.addWidget(self.QTB_selected_trace, 1, 1, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.layoutWidget10)
        self.label_29.setObjectName("label_29")
        self.gridLayout_5.addWidget(self.label_29, 2, 0, 1, 1)
        self.QTB_ratio = QtWidgets.QTextBrowser(self.layoutWidget10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.QTB_ratio.sizePolicy().hasHeightForWidth())
        self.QTB_ratio.setSizePolicy(sizePolicy)
        self.QTB_ratio.setMaximumSize(QtCore.QSize(101, 26))
        self.QTB_ratio.setObjectName("QTB_ratio")
        self.gridLayout_5.addWidget(self.QTB_ratio, 2, 1, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.layoutWidget10)
        self.label_30.setObjectName("label_30")
        self.gridLayout_5.addWidget(self.label_30, 2, 2, 1, 1)
        self.Function.addTab(self.Select, "")
        self.Fitting = QtWidgets.QWidget()
        self.Fitting.setObjectName("Fitting")
        self.tabWidget = QtWidgets.QTabWidget(self.Fitting)
        self.tabWidget.setGeometry(QtCore.QRect(-1, -2, 237, 271))
        self.tabWidget.setObjectName("tabWidget")
        self.Fit1_para = QtWidgets.QWidget()
        self.Fit1_para.setObjectName("Fit1_para")
        self.layoutWidget11 = QtWidgets.QWidget(self.Fit1_para)
        self.layoutWidget11.setGeometry(QtCore.QRect(1, 11, 230, 151))
        self.layoutWidget11.setObjectName("layoutWidget11")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget11)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_10 = QtWidgets.QLabel(self.layoutWidget11)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 0, 0, 1, 1)
        self.QPT_f1_a1 = QtWidgets.QPlainTextEdit(self.layoutWidget11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.QPT_f1_a1.sizePolicy().hasHeightForWidth())
        self.QPT_f1_a1.setSizePolicy(sizePolicy)
        self.QPT_f1_a1.setMaximumSize(QtCore.QSize(93, 25))
        self.QPT_f1_a1.setObjectName("QPT_f1_a1")
        self.gridLayout.addWidget(self.QPT_f1_a1, 0, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.layoutWidget11)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 0, 2, 1, 1)
        self.QPT_f1_b1 = QtWidgets.QPlainTextEdit(self.layoutWidget11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.QPT_f1_b1.sizePolicy().hasHeightForWidth())
        self.QPT_f1_b1.setSizePolicy(sizePolicy)
        self.QPT_f1_b1.setMaximumSize(QtCore.QSize(93, 25))
        self.QPT_f1_b1.setObjectName("QPT_f1_b1")
        self.gridLayout.addWidget(self.QPT_f1_b1, 0, 3, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.layoutWidget11)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 1, 0, 1, 1)
        self.QPT_f1_c1 = QtWidgets.QPlainTextEdit(self.layoutWidget11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.QPT_f1_c1.sizePolicy().hasHeightForWidth())
        self.QPT_f1_c1.setSizePolicy(sizePolicy)
        self.QPT_f1_c1.setMaximumSize(QtCore.QSize(93, 25))
        self.QPT_f1_c1.setObjectName("QPT_f1_c1")
        self.gridLayout.addWidget(self.QPT_f1_c1, 1, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.layoutWidget11)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 1, 2, 1, 1)
        self.QPT_f1_d1 = QtWidgets.QPlainTextEdit(self.layoutWidget11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.QPT_f1_d1.sizePolicy().hasHeightForWidth())
        self.QPT_f1_d1.setSizePolicy(sizePolicy)
        self.QPT_f1_d1.setMaximumSize(QtCore.QSize(93, 25))
        self.QPT_f1_d1.setObjectName("QPT_f1_d1")
        self.gridLayout.addWidget(self.QPT_f1_d1, 1, 3, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.layoutWidget11)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 2, 0, 1, 1)
        self.QPT_f1_a2 = QtWidgets.QPlainTextEdit(self.layoutWidget11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.QPT_f1_a2.sizePolicy().hasHeightForWidth())
        self.QPT_f1_a2.setSizePolicy(sizePolicy)
        self.QPT_f1_a2.setMaximumSize(QtCore.QSize(93, 25))
        self.QPT_f1_a2.setObjectName("QPT_f1_a2")
        self.gridLayout.addWidget(self.QPT_f1_a2, 2, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.layoutWidget11)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 2, 2, 1, 1)
        self.QPT_f1_b2 = QtWidgets.QPlainTextEdit(self.layoutWidget11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.QPT_f1_b2.sizePolicy().hasHeightForWidth())
        self.QPT_f1_b2.setSizePolicy(sizePolicy)
        self.QPT_f1_b2.setMaximumSize(QtCore.QSize(93, 25))
        self.QPT_f1_b2.setObjectName("QPT_f1_b2")
        self.gridLayout.addWidget(self.QPT_f1_b2, 2, 3, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.layoutWidget11)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 3, 0, 1, 1)
        self.QPT_f1_c2 = QtWidgets.QPlainTextEdit(self.layoutWidget11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.QPT_f1_c2.sizePolicy().hasHeightForWidth())
        self.QPT_f1_c2.setSizePolicy(sizePolicy)
        self.QPT_f1_c2.setMaximumSize(QtCore.QSize(93, 25))
        self.QPT_f1_c2.setObjectName("QPT_f1_c2")
        self.gridLayout.addWidget(self.QPT_f1_c2, 3, 1, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.layoutWidget11)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.gridLayout.addWidget(self.label_17, 3, 2, 1, 1)
        self.QPT_f1_d2 = QtWidgets.QPlainTextEdit(self.layoutWidget11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.QPT_f1_d2.sizePolicy().hasHeightForWidth())
        self.QPT_f1_d2.setSizePolicy(sizePolicy)
        self.QPT_f1_d2.setMaximumSize(QtCore.QSize(93, 25))
        self.QPT_f1_d2.setObjectName("QPT_f1_d2")
        self.gridLayout.addWidget(self.QPT_f1_d2, 3, 3, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.layoutWidget11)
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.gridLayout.addWidget(self.label_18, 4, 1, 1, 1)
        self.QPT_f1_offset = QtWidgets.QPlainTextEdit(self.layoutWidget11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.QPT_f1_offset.sizePolicy().hasHeightForWidth())
        self.QPT_f1_offset.setSizePolicy(sizePolicy)
        self.QPT_f1_offset.setMaximumSize(QtCore.QSize(93, 25))
        self.QPT_f1_offset.setObjectName("QPT_f1_offset")
        self.gridLayout.addWidget(self.QPT_f1_offset, 4, 3, 1, 1)
        self.tabWidget.addTab(self.Fit1_para, "")
        self.Fit2_para = QtWidgets.QWidget()
        self.Fit2_para.setObjectName("Fit2_para")
        self.layoutWidget12 = QtWidgets.QWidget(self.Fit2_para)
        self.layoutWidget12.setGeometry(QtCore.QRect(0, 13, 220, 227))
        self.layoutWidget12.setObjectName("layoutWidget12")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.layoutWidget12)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_31 = QtWidgets.QLabel(self.layoutWidget12)
        self.label_31.setObjectName("label_31")
        self.gridLayout_6.addWidget(self.label_31, 0, 0, 1, 1)
        self.QPT_f2_a1 = QtWidgets.QPlainTextEdit(self.layoutWidget12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.QPT_f2_a1.sizePolicy().hasHeightForWidth())
        self.QPT_f2_a1.setSizePolicy(sizePolicy)
        self.QPT_f2_a1.setMaximumSize(QtCore.QSize(88, 27))
        self.QPT_f2_a1.setObjectName("QPT_f2_a1")
        self.gridLayout_6.addWidget(self.QPT_f2_a1, 0, 1, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.layoutWidget12)
        self.label_32.setObjectName("label_32")
        self.gridLayout_6.addWidget(self.label_32, 0, 2, 1, 1)
        self.QPT_f2_a2 = QtWidgets.QPlainTextEdit(self.layoutWidget12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.QPT_f2_a2.sizePolicy().hasHeightForWidth())
        self.QPT_f2_a2.setSizePolicy(sizePolicy)
        self.QPT_f2_a2.setMaximumSize(QtCore.QSize(88, 27))
        self.QPT_f2_a2.setObjectName("QPT_f2_a2")
        self.gridLayout_6.addWidget(self.QPT_f2_a2, 0, 3, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.layoutWidget12)
        self.label_33.setObjectName("label_33")
        self.gridLayout_6.addWidget(self.label_33, 1, 0, 1, 1)
        self.QPT_f2_b1 = QtWidgets.QPlainTextEdit(self.layoutWidget12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.QPT_f2_b1.sizePolicy().hasHeightForWidth())
        self.QPT_f2_b1.setSizePolicy(sizePolicy)
        self.QPT_f2_b1.setMaximumSize(QtCore.QSize(88, 27))
        self.QPT_f2_b1.setObjectName("QPT_f2_b1")
        self.gridLayout_6.addWidget(self.QPT_f2_b1, 1, 1, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.layoutWidget12)
        self.label_34.setObjectName("label_34")
        self.gridLayout_6.addWidget(self.label_34, 1, 2, 1, 1)
        self.QPT_f2_b2 = QtWidgets.QPlainTextEdit(self.layoutWidget12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.QPT_f2_b2.sizePolicy().hasHeightForWidth())
        self.QPT_f2_b2.setSizePolicy(sizePolicy)
        self.QPT_f2_b2.setMaximumSize(QtCore.QSize(88, 27))
        self.QPT_f2_b2.setObjectName("QPT_f2_b2")
        self.gridLayout_6.addWidget(self.QPT_f2_b2, 1, 3, 1, 1)
        self.label_35 = QtWidgets.QLabel(self.layoutWidget12)
        self.label_35.setObjectName("label_35")
        self.gridLayout_6.addWidget(self.label_35, 2, 0, 1, 1)
        self.QPT_f2_c1 = QtWidgets.QPlainTextEdit(self.layoutWidget12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.QPT_f2_c1.sizePolicy().hasHeightForWidth())
        self.QPT_f2_c1.setSizePolicy(sizePolicy)
        self.QPT_f2_c1.setMaximumSize(QtCore.QSize(88, 27))
        self.QPT_f2_c1.setObjectName("QPT_f2_c1")
        self.gridLayout_6.addWidget(self.QPT_f2_c1, 2, 1, 1, 1)
        self.label_36 = QtWidgets.QLabel(self.layoutWidget12)
        self.label_36.setObjectName("label_36")
        self.gridLayout_6.addWidget(self.label_36, 2, 2, 1, 1)
        self.QPT_f2_c2 = QtWidgets.QPlainTextEdit(self.layoutWidget12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.QPT_f2_c2.sizePolicy().hasHeightForWidth())
        self.QPT_f2_c2.setSizePolicy(sizePolicy)
        self.QPT_f2_c2.setMaximumSize(QtCore.QSize(88, 27))
        self.QPT_f2_c2.setObjectName("QPT_f2_c2")
        self.gridLayout_6.addWidget(self.QPT_f2_c2, 2, 3, 1, 1)
        self.label_37 = QtWidgets.QLabel(self.layoutWidget12)
        self.label_37.setObjectName("label_37")
        self.gridLayout_6.addWidget(self.label_37, 3, 0, 1, 1)
        self.QPT_f2_d1 = QtWidgets.QPlainTextEdit(self.layoutWidget12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.QPT_f2_d1.sizePolicy().hasHeightForWidth())
        self.QPT_f2_d1.setSizePolicy(sizePolicy)
        self.QPT_f2_d1.setMaximumSize(QtCore.QSize(88, 27))
        self.QPT_f2_d1.setObjectName("QPT_f2_d1")
        self.gridLayout_6.addWidget(self.QPT_f2_d1, 3, 1, 1, 1)
        self.label_38 = QtWidgets.QLabel(self.layoutWidget12)
        self.label_38.setObjectName("label_38")
        self.gridLayout_6.addWidget(self.label_38, 3, 2, 1, 1)
        self.QPT_f2_d2 = QtWidgets.QPlainTextEdit(self.layoutWidget12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.QPT_f2_d2.sizePolicy().hasHeightForWidth())
        self.QPT_f2_d2.setSizePolicy(sizePolicy)
        self.QPT_f2_d2.setMaximumSize(QtCore.QSize(88, 27))
        self.QPT_f2_d2.setObjectName("QPT_f2_d2")
        self.gridLayout_6.addWidget(self.QPT_f2_d2, 3, 3, 1, 1)
        self.label_39 = QtWidgets.QLabel(self.layoutWidget12)
        self.label_39.setObjectName("label_39")
        self.gridLayout_6.addWidget(self.label_39, 4, 0, 1, 1)
        self.QPT_f2_e1 = QtWidgets.QPlainTextEdit(self.layoutWidget12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.QPT_f2_e1.sizePolicy().hasHeightForWidth())
        self.QPT_f2_e1.setSizePolicy(sizePolicy)
        self.QPT_f2_e1.setMaximumSize(QtCore.QSize(88, 27))
        self.QPT_f2_e1.setObjectName("QPT_f2_e1")
        self.gridLayout_6.addWidget(self.QPT_f2_e1, 4, 1, 1, 1)
        self.label_40 = QtWidgets.QLabel(self.layoutWidget12)
        self.label_40.setObjectName("label_40")
        self.gridLayout_6.addWidget(self.label_40, 4, 2, 1, 1)
        self.QPT_f2_e2 = QtWidgets.QPlainTextEdit(self.layoutWidget12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.QPT_f2_e2.sizePolicy().hasHeightForWidth())
        self.QPT_f2_e2.setSizePolicy(sizePolicy)
        self.QPT_f2_e2.setMaximumSize(QtCore.QSize(88, 27))
        self.QPT_f2_e2.setObjectName("QPT_f2_e2")
        self.gridLayout_6.addWidget(self.QPT_f2_e2, 4, 3, 1, 1)
        self.label_41 = QtWidgets.QLabel(self.layoutWidget12)
        self.label_41.setObjectName("label_41")
        self.gridLayout_6.addWidget(self.label_41, 5, 0, 1, 1)
        self.QPT_f2_f1 = QtWidgets.QPlainTextEdit(self.layoutWidget12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.QPT_f2_f1.sizePolicy().hasHeightForWidth())
        self.QPT_f2_f1.setSizePolicy(sizePolicy)
        self.QPT_f2_f1.setMaximumSize(QtCore.QSize(88, 27))
        self.QPT_f2_f1.setObjectName("QPT_f2_f1")
        self.gridLayout_6.addWidget(self.QPT_f2_f1, 5, 1, 1, 1)
        self.label_42 = QtWidgets.QLabel(self.layoutWidget12)
        self.label_42.setObjectName("label_42")
        self.gridLayout_6.addWidget(self.label_42, 5, 2, 1, 1)
        self.QPT_f2_f2 = QtWidgets.QPlainTextEdit(self.layoutWidget12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.QPT_f2_f2.sizePolicy().hasHeightForWidth())
        self.QPT_f2_f2.setSizePolicy(sizePolicy)
        self.QPT_f2_f2.setMaximumSize(QtCore.QSize(88, 27))
        self.QPT_f2_f2.setObjectName("QPT_f2_f2")
        self.gridLayout_6.addWidget(self.QPT_f2_f2, 5, 3, 1, 1)
        self.label_58 = QtWidgets.QLabel(self.layoutWidget12)
        self.label_58.setText("")
        self.label_58.setObjectName("label_58")
        self.gridLayout_6.addWidget(self.label_58, 6, 0, 1, 1)
        self.label_56 = QtWidgets.QLabel(self.layoutWidget12)
        self.label_56.setAlignment(QtCore.Qt.AlignCenter)
        self.label_56.setObjectName("label_56")
        self.gridLayout_6.addWidget(self.label_56, 6, 1, 1, 1)
        self.label_57 = QtWidgets.QLabel(self.layoutWidget12)
        self.label_57.setText("")
        self.label_57.setObjectName("label_57")
        self.gridLayout_6.addWidget(self.label_57, 6, 2, 1, 1)
        self.QPT_f2_offset = QtWidgets.QPlainTextEdit(self.layoutWidget12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.QPT_f2_offset.sizePolicy().hasHeightForWidth())
        self.QPT_f2_offset.setSizePolicy(sizePolicy)
        self.QPT_f2_offset.setMinimumSize(QtCore.QSize(88, 27))
        self.QPT_f2_offset.setMaximumSize(QtCore.QSize(88, 27))
        self.QPT_f2_offset.setObjectName("QPT_f2_offset")
        self.gridLayout_6.addWidget(self.QPT_f2_offset, 6, 3, 1, 1)
        self.tabWidget.addTab(self.Fit2_para, "")
        self.Fit3_para = QtWidgets.QWidget()
        self.Fit3_para.setObjectName("Fit3_para")
        self.layoutWidget13 = QtWidgets.QWidget(self.Fit3_para)
        self.layoutWidget13.setGeometry(QtCore.QRect(1, 12, 228, 89))
        self.layoutWidget13.setObjectName("layoutWidget13")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.layoutWidget13)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_44 = QtWidgets.QLabel(self.layoutWidget13)
        self.label_44.setObjectName("label_44")
        self.gridLayout_8.addWidget(self.label_44, 0, 0, 1, 1)
        self.QPT_f3_a1 = QtWidgets.QPlainTextEdit(self.layoutWidget13)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.QPT_f3_a1.sizePolicy().hasHeightForWidth())
        self.QPT_f3_a1.setSizePolicy(sizePolicy)
        self.QPT_f3_a1.setMaximumSize(QtCore.QSize(80, 25))
        self.QPT_f3_a1.setObjectName("QPT_f3_a1")
        self.gridLayout_8.addWidget(self.QPT_f3_a1, 0, 1, 1, 1)
        self.label_45 = QtWidgets.QLabel(self.layoutWidget13)
        self.label_45.setAlignment(QtCore.Qt.AlignCenter)
        self.label_45.setObjectName("label_45")
        self.gridLayout_8.addWidget(self.label_45, 0, 2, 1, 1)
        self.QPT_f3_b1 = QtWidgets.QPlainTextEdit(self.layoutWidget13)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.QPT_f3_b1.sizePolicy().hasHeightForWidth())
        self.QPT_f3_b1.setSizePolicy(sizePolicy)
        self.QPT_f3_b1.setMaximumSize(QtCore.QSize(80, 25))
        self.QPT_f3_b1.setObjectName("QPT_f3_b1")
        self.gridLayout_8.addWidget(self.QPT_f3_b1, 0, 3, 1, 1)
        self.label_55 = QtWidgets.QLabel(self.layoutWidget13)
        self.label_55.setObjectName("label_55")
        self.gridLayout_8.addWidget(self.label_55, 1, 0, 1, 1)
        self.QPT_f3_a2 = QtWidgets.QPlainTextEdit(self.layoutWidget13)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.QPT_f3_a2.sizePolicy().hasHeightForWidth())
        self.QPT_f3_a2.setSizePolicy(sizePolicy)
        self.QPT_f3_a2.setMaximumSize(QtCore.QSize(80, 25))
        self.QPT_f3_a2.setObjectName("QPT_f3_a2")
        self.gridLayout_8.addWidget(self.QPT_f3_a2, 1, 1, 1, 1)
        self.label_54 = QtWidgets.QLabel(self.layoutWidget13)
        self.label_54.setAlignment(QtCore.Qt.AlignCenter)
        self.label_54.setObjectName("label_54")
        self.gridLayout_8.addWidget(self.label_54, 1, 2, 1, 1)
        self.QPT_f3_b2 = QtWidgets.QPlainTextEdit(self.layoutWidget13)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.QPT_f3_b2.sizePolicy().hasHeightForWidth())
        self.QPT_f3_b2.setSizePolicy(sizePolicy)
        self.QPT_f3_b2.setMaximumSize(QtCore.QSize(80, 25))
        self.QPT_f3_b2.setObjectName("QPT_f3_b2")
        self.gridLayout_8.addWidget(self.QPT_f3_b2, 1, 3, 1, 1)
        self.label_50 = QtWidgets.QLabel(self.layoutWidget13)
        self.label_50.setObjectName("label_50")
        self.gridLayout_8.addWidget(self.label_50, 2, 0, 1, 1)
        self.QPT_f3_r1 = QtWidgets.QPlainTextEdit(self.layoutWidget13)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.QPT_f3_r1.sizePolicy().hasHeightForWidth())
        self.QPT_f3_r1.setSizePolicy(sizePolicy)
        self.QPT_f3_r1.setMaximumSize(QtCore.QSize(80, 25))
        self.QPT_f3_r1.setObjectName("QPT_f3_r1")
        self.gridLayout_8.addWidget(self.QPT_f3_r1, 2, 1, 1, 1)
        self.label_59 = QtWidgets.QLabel(self.layoutWidget13)
        self.label_59.setAlignment(QtCore.Qt.AlignCenter)
        self.label_59.setObjectName("label_59")
        self.gridLayout_8.addWidget(self.label_59, 2, 2, 1, 1)
        self.QPT_f3_offset = QtWidgets.QPlainTextEdit(self.layoutWidget13)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.QPT_f3_offset.sizePolicy().hasHeightForWidth())
        self.QPT_f3_offset.setSizePolicy(sizePolicy)
        self.QPT_f3_offset.setMinimumSize(QtCore.QSize(80, 25))
        self.QPT_f3_offset.setMaximumSize(QtCore.QSize(80, 25))
        self.QPT_f3_offset.setObjectName("QPT_f3_offset")
        self.gridLayout_8.addWidget(self.QPT_f3_offset, 2, 3, 1, 1)
        self.tabWidget.addTab(self.Fit3_para, "")
        self.Function.addTab(self.Fitting, "")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(1102, 672, 241, 23))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(1101, 530, 241, 131))
        self.textBrowser.setObjectName("textBrowser")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(1106, 510, 54, 12))
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1350, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        self.tabWidget_fig.setCurrentIndex(0)
        self.Function.setCurrentIndex(0)
        self.Parameter.setCurrentIndex(0)
        self.toolBox.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "XMe_V1.3"))
        self.Load_btn.setText(_translate("MainWindow", "Load File"))
        self.Run_btn.setText(_translate("MainWindow", "Run"))
        self.Conduct_Length_fig.setTitle(_translate("MainWindow", "2D-Conductance"))
        self.Conductance_fig.setTitle(_translate("MainWindow", "1D-Conductance"))
        self.Length_fig.setTitle(_translate("MainWindow", "Length"))
        self.tabWidget_fig.setTabText(self.tabWidget_fig.indexOf(self.Figure), _translate("MainWindow", "Figure"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Trace"))
        self.QPB_Add_to_save.setText(_translate("MainWindow", "add_to_save"))
        self.QPB_save_all_trace.setText(_translate("MainWindow", "save_all_trace"))
        self.QPB_save_add.setText(_translate("MainWindow", "save_select"))
        self.QPB_Prev.setText(_translate("MainWindow", "Prev"))
        self.QPB_First.setText(_translate("MainWindow", "First"))
        self.QPB_Next.setText(_translate("MainWindow", "Next"))
        self.QPB_Last.setText(_translate("MainWindow", "Last"))
        self.tabWidget_fig.setTabText(self.tabWidget_fig.indexOf(self.Single_Trace), _translate("MainWindow", "Single_Trace"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Current-Frequency"))
        self.tabWidget_fig.setTabText(self.tabWidget_fig.indexOf(self.Frequency), _translate("MainWindow", "Frequency"))
        self.process.setTitle(_translate("MainWindow", "process"))
        self.QRB_open.setText(_translate("MainWindow", "Open"))
        self.QRB_close.setText(_translate("MainWindow", "Close"))
        self.groupBox_6.setTitle(_translate("MainWindow", "style"))
        self.groupBox_11.setTitle(_translate("MainWindow", "fitting mode"))
        self.FitMode_box.setItemText(0, _translate("MainWindow", "Fit1"))
        self.FitMode_box.setItemText(1, _translate("MainWindow", "Fit2"))
        self.FitMode_box.setItemText(2, _translate("MainWindow", "Fit3"))
        self.QPB_redraw.setText(_translate("MainWindow", "Redraw"))
        self.QPB_reset.setText(_translate("MainWindow", "Reset"))
        self.QPB_save_all.setText(_translate("MainWindow", "Save"))
        self.QPB_save_goodtrace.setText(_translate("MainWindow", "GoodTrace"))
        self.label_52.setText(_translate("MainWindow", "add_length"))
        self.QPT_add_length.setPlainText(_translate("MainWindow", "500"))
        self.QPB_update.setText(_translate("MainWindow", "Update"))
        self.QPT_high_cut.setPlainText(_translate("MainWindow", "1.2"))
        self.QPT_low_cut.setPlainText(_translate("MainWindow", "-6"))
        self.label_6.setText(_translate("MainWindow", "high_cut"))
        self.label_7.setText(_translate("MainWindow", "low_cut"))
        self.QPT_high_length.setPlainText(_translate("MainWindow", "-0.3"))
        self.QPT_low_length.setPlainText(_translate("MainWindow", "-6"))
        self.label_8.setText(_translate("MainWindow", "high_length"))
        self.label_9.setText(_translate("MainWindow", "low_length"))
        self.label_64.setText(_translate("MainWindow", "Zero_set"))
        self.QPT_zero_set.setPlainText(_translate("MainWindow", "-0.3"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.Cut_set), _translate("MainWindow", "Cut_set"))
        self.QPT_sampling_rate.setPlainText(_translate("MainWindow", "20000"))
        self.label_4.setText(_translate("MainWindow", "Hz"))
        self.label_63.setText(_translate("MainWindow", "V/s"))
        self.label.setText(_translate("MainWindow", "sampling_rate"))
        self.label_62.setText(_translate("MainWindow", "piezo_rate"))
        self.QPT_biasV.setPlainText(_translate("MainWindow", "0.1"))
        self.label_61.setText(_translate("MainWindow", "V"))
        self.QPT_strecting_rate.setPlainText(_translate("MainWindow", "10"))
        self.label_5.setText(_translate("MainWindow", "nm/s"))
        self.label_60.setText(_translate("MainWindow", "bias_V"))
        self.label_3.setText(_translate("MainWindow", "stretching_rate"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.Para), _translate("MainWindow", "Basic_para"))
        self.Parameter.setTabText(self.Parameter.indexOf(self.Basic), _translate("MainWindow", "Basic"))
        self.groupBox.setTitle(_translate("MainWindow", "2D"))
        self.label_43.setText(_translate("MainWindow", "bins(x,y)"))
        self.QPT_2D_binsx.setPlainText(_translate("MainWindow", "500"))
        self.QPT_2D_binsy.setPlainText(_translate("MainWindow", "800"))
        self.label_46.setText(_translate("MainWindow", "x_lim"))
        self.QPT_2D_xlim_l.setPlainText(_translate("MainWindow", "-0.2"))
        self.QPT_2D_xlim_r.setPlainText(_translate("MainWindow", "2"))
        self.label_47.setText(_translate("MainWindow", "y_lim"))
        self.QPT_2D_ylim_l.setPlainText(_translate("MainWindow", "-8"))
        self.QPT_2D_ylim_r.setPlainText(_translate("MainWindow", "1.5"))
        self.groupBox_2.setTitle(_translate("MainWindow", "1D"))
        self.label_48.setText(_translate("MainWindow", "bins"))
        self.QPT_1D_bins.setPlainText(_translate("MainWindow", "800"))
        self.QPB_1D_color.setText(_translate("MainWindow", "Color"))
        self.label_53.setText(_translate("MainWindow", "x_lim"))
        self.QPT_1D_xlim_l.setPlainText(_translate("MainWindow", "-8"))
        self.QPT_1D_xlim_r.setPlainText(_translate("MainWindow", "1.5"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Length"))
        self.label_49.setText(_translate("MainWindow", "bins"))
        self.QPT_leng_xlim_l.setPlainText(_translate("MainWindow", "0"))
        self.QPT_leng_bins.setPlainText(_translate("MainWindow", "100"))
        self.QPT_leng_xlim_r.setPlainText(_translate("MainWindow", "3"))
        self.label_51.setText(_translate("MainWindow", "x_lim"))
        self.Parameter.setTabText(self.Parameter.indexOf(self.Fig_set), _translate("MainWindow", "Fig_set"))
        self.Function.setTabText(self.Function.indexOf(self.Analysis), _translate("MainWindow", "Analysis"))
        self.QPT_start1.setPlainText(_translate("MainWindow", "-2"))
        self.QPT_end1.setPlainText(_translate("MainWindow", "-3"))
        self.label_19.setText(_translate("MainWindow", "start1"))
        self.label_20.setText(_translate("MainWindow", "end1"))
        self.QPT_lower_limit1.setPlainText(_translate("MainWindow", "-55"))
        self.QPT_upper_limit1.setPlainText(_translate("MainWindow", "55"))
        self.label_21.setText(_translate("MainWindow", "lower limit1"))
        self.label_22.setText(_translate("MainWindow", "upper limit1"))
        self.QPT_start2.setPlainText(_translate("MainWindow", "-4"))
        self.QPT_end2.setPlainText(_translate("MainWindow", "-6"))
        self.label_23.setText(_translate("MainWindow", "start2"))
        self.label_24.setText(_translate("MainWindow", "end2"))
        self.QPT_lower_limit2.setPlainText(_translate("MainWindow", "-55"))
        self.QPT_upper_limit2.setPlainText(_translate("MainWindow", "55"))
        self.label_25.setText(_translate("MainWindow", "lower limit2"))
        self.label_26.setText(_translate("MainWindow", "upper limit2"))
        self.label_27.setText(_translate("MainWindow", "All Trace:"))
        self.label_28.setText(_translate("MainWindow", "Selected Trace:"))
        self.label_29.setText(_translate("MainWindow", "Ratio:"))
        self.label_30.setText(_translate("MainWindow", "%"))
        self.Function.setTabText(self.Function.indexOf(self.Select), _translate("MainWindow", "Select"))
        self.label_10.setText(_translate("MainWindow", "a1"))
        self.QPT_f1_a1.setPlainText(_translate("MainWindow", "-9.1137"))
        self.label_11.setText(_translate("MainWindow", "b1"))
        self.QPT_f1_b1.setPlainText(_translate("MainWindow", "-27.646"))
        self.label_12.setText(_translate("MainWindow", "c1"))
        self.QPT_f1_c1.setPlainText(_translate("MainWindow", "-1.1614e-11"))
        self.label_13.setText(_translate("MainWindow", "d1"))
        self.QPT_f1_d1.setPlainText(_translate("MainWindow", "4.1597e-13"))
        self.label_14.setText(_translate("MainWindow", "a2"))
        self.QPT_f1_a2.setPlainText(_translate("MainWindow", "9.2183"))
        self.label_15.setText(_translate("MainWindow", "b2"))
        self.QPT_f1_b2.setPlainText(_translate("MainWindow", "-27.8018"))
        self.label_16.setText(_translate("MainWindow", "c2"))
        self.QPT_f1_c2.setPlainText(_translate("MainWindow", "1.1899e-11"))
        self.label_17.setText(_translate("MainWindow", "d2"))
        self.QPT_f1_d2.setPlainText(_translate("MainWindow", "-1.4714e-13"))
        self.label_18.setText(_translate("MainWindow", "offset"))
        self.QPT_f1_offset.setPlainText(_translate("MainWindow", "0"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Fit1_para), _translate("MainWindow", "Fit1"))
        self.label_31.setText(_translate("MainWindow", "a1"))
        self.QPT_f2_a1.setPlainText(_translate("MainWindow", "7.11645"))
        self.label_32.setText(_translate("MainWindow", "a2"))
        self.QPT_f2_a2.setPlainText(_translate("MainWindow", "12.59542"))
        self.label_33.setText(_translate("MainWindow", "b1"))
        self.QPT_f2_b1.setPlainText(_translate("MainWindow", "-32.28028"))
        self.label_34.setText(_translate("MainWindow", "b2"))
        self.QPT_f2_b2.setPlainText(_translate("MainWindow", "-23.00707"))
        self.label_35.setText(_translate("MainWindow", "c1"))
        self.QPT_f2_c1.setPlainText(_translate("MainWindow", "-1.16402"))
        self.label_36.setText(_translate("MainWindow", "c2"))
        self.QPT_f2_c2.setPlainText(_translate("MainWindow", "-1.5182"))
        self.label_37.setText(_translate("MainWindow", "d1"))
        self.QPT_f2_d1.setPlainText(_translate("MainWindow", "4.42553"))
        self.label_38.setText(_translate("MainWindow", "d2"))
        self.QPT_f2_d2.setPlainText(_translate("MainWindow", "-6.14423"))
        self.label_39.setText(_translate("MainWindow", "e1"))
        self.QPT_f2_e1.setPlainText(_translate("MainWindow", "0.01091"))
        self.label_40.setText(_translate("MainWindow", "e2"))
        self.QPT_f2_e2.setPlainText(_translate("MainWindow", "0.2286"))
        self.label_41.setText(_translate("MainWindow", "f1"))
        self.QPT_f2_f1.setPlainText(_translate("MainWindow", "-1.17779"))
        self.label_42.setText(_translate("MainWindow", "f2"))
        self.QPT_f2_f2.setPlainText(_translate("MainWindow", "-1.2272"))
        self.label_56.setText(_translate("MainWindow", "offset"))
        self.QPT_f2_offset.setPlainText(_translate("MainWindow", "0"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Fit2_para), _translate("MainWindow", "Fit2"))
        self.label_44.setText(_translate("MainWindow", "a1"))
        self.QPT_f3_a1.setPlainText(_translate("MainWindow", "3.1435"))
        self.label_45.setText(_translate("MainWindow", "b1"))
        self.QPT_f3_b1.setPlainText(_translate("MainWindow", "-14.62"))
        self.label_55.setText(_translate("MainWindow", "a2"))
        self.QPT_f3_a2.setPlainText(_translate("MainWindow", "-3.1009"))
        self.label_54.setText(_translate("MainWindow", "b2"))
        self.QPT_f3_b2.setPlainText(_translate("MainWindow", "-14.456"))
        self.label_50.setText(_translate("MainWindow", "R1"))
        self.QPT_f3_r1.setPlainText(_translate("MainWindow", "0"))
        self.label_59.setText(_translate("MainWindow", "offset"))
        self.QPT_f3_offset.setPlainText(_translate("MainWindow", "0"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Fit3_para), _translate("MainWindow", "Fit3"))
        self.Function.setTabText(self.Function.indexOf(self.Fitting), _translate("MainWindow", "Fitting"))
        self.label_2.setText(_translate("MainWindow", "Log"))
